

#ifndef _LEDS_DEV_V_h
#define _LEDS_DEV_V_h



#define LEDS_DEF_MAX_BRI 255

#define LEDS_DEF_COLOR_SELECT_WHITE 254
#define LEDS_DEF_COLOR_SELECT_RAINBOW_PAL 20
#define LEDS_DEF_COLOR_SELECT_RAINBOW_STRIPED_PAL 21

#define LEDS_DEF_BIN_NO_BIN 255


#define LEDS_DEF_START_LED 0
#define LEDS_DEF_NR_LEDs 0


// FFT

#define LEDS_DEF_FFT_EXTEND 0
#define LEDS_DEF_FFT_OFFSET 0


// PAL

#define LEDS_DEF_PAL_START_INDEX 0
#define LEDS_DEF_PAL_SPEED   16
#define LEDS_DEF_PAL_COMPRESSION 8   
#define LEDS_DEF_PALAUTOCOMPRESSION    1


// Modify Layer

#define LEDS_DEF_MODIFY_ROTATEFIXED  0
#define LEDS_DEF_MODIFY_ROTATEFULLFRAMES 500          // 
#define LEDS_DEF_MODIFY_ROTATETRIGGERBIN 255        // No Bin


// FX1
#define LEDS_DEF_FX1_FADE 5


// EYES
#define LEDS_DEF_EYES_ON_FRAMES 60
#define LEDS_DEF_EYES_PAUSE_FRAMES  10
#define LEDS_DEF_EYES_WIDTH  1
#define LEDS_DEF_EYES_SPACE   1
#define LEDS_DEF_EYES_FADEVAL  5  

#define LEDS_DEF_GLITTER_VAL   25

#define LEDS_DEF_DOTS_SPEED 5
#define LEDS_DEF_DOTS_PAL_SPEED 32
#define LEDS_DEF_DOTS_NR   1

#define LEDS_DEF_SHIMMER_



#endif